DROP EXTENSION pgcrypto;
DROP TABLE scheduled_transactions;
DROP TABLE transfers CASCADE;
DROP TABLE categories CASCADE;
DROP TABLE transactions CASCADE;
DROP TABLE app_users CASCADE;
DROP TABLE accounts CASCADE;
DROP TYPE category_types CASCADE;
DROP TYPE repeat_frequencies CASCADE;
DROP SEQUENCE transactions_transfers_id_seq;