
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Fetch the full initial payload (accounts, categories, scheduled transactions). Called once
 * on app start to populate the frontend store.
 */
async getInitialData() : Promise<Result<InitialData, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_initial_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createAccount(name: string) : Promise<Result<GetAccount, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_account", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAccounts() : Promise<Result<GetAccount[], { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAccount(accountId: number) : Promise<Result<GetAccount, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAccount(accountId: number, name: string) : Promise<Result<GetAccount, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_account", { accountId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAccount(accountId: number) : Promise<Result<Account, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_account", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCategory(req: PostCategory) : Promise<Result<Category, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_category", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCategories() : Promise<Result<Category[], { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Filter categories by type. Replaces the former `/categories/expense` and
 * `/categories/income` routes; the type is matched case-insensitively.
 */
async getCategoriesByType(categoryType: string) : Promise<Result<Category[], { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_categories_by_type", { categoryType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCategory(categoryId: number) : Promise<Result<Category, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_category", { categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCategory(categoryId: number, req: PostCategory) : Promise<Result<Category, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_category", { categoryId, req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCategory(categoryId: number) : Promise<Result<Category, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_category", { categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTransaction(accountId: number, req: PostTransaction) : Promise<Result<Transaction, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_transaction", { accountId, req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTransactionsForAccount(accountId: number) : Promise<Result<TransactionTransferJoined[], { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transactions_for_account", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTransaction(transactionId: number) : Promise<Result<TransactionTransferJoined, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transaction", { transactionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTransaction(transactionId: number, req: PatchTransaction) : Promise<Result<Transaction, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_transaction", { transactionId, req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTransaction(transactionId: number) : Promise<Result<Transaction, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_transaction", { transactionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTransfer(originAccount: number, destinationAccount: number, req: PostTransfer) : Promise<Result<Transfer, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_transfer", { originAccount, destinationAccount, req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTransfer(transferId: number) : Promise<Result<Transfer, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transfer", { transferId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTransfer(transferId: number, req: PatchTransfer) : Promise<Result<Transfer, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_transfer", { transferId, req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTransfer(transferId: number) : Promise<Result<Transfer, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_transfer", { transferId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createScheduledTransaction(req: PostScheduledTransaction) : Promise<Result<GetScheduledTransaction, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_scheduled_transaction", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScheduledTransactions() : Promise<Result<GetScheduledTransaction[], { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_scheduled_transactions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScheduledTransaction(scheduledTransactionId: number) : Promise<Result<GetScheduledTransaction, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_scheduled_transaction", { scheduledTransactionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateScheduledTransaction(scheduledTransactionId: number, req: PostScheduledTransaction) : Promise<Result<GetScheduledTransaction, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_scheduled_transaction", { scheduledTransactionId, req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteScheduledTransaction(scheduledTransactionId: number) : Promise<Result<ScheduledTransaction, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_scheduled_transaction", { scheduledTransactionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async payScheduledTransaction(scheduledTransactionId: number, req: PostScheduledTransactionPay) : Promise<Result<ScheduledTransaction, { status: number; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pay_scheduled_transaction", { scheduledTransactionId, req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Account = { id: number; name: string }
export type Category = { id: number; categorytype: CategoryTypes; name: string }
export type CategoryTypes = "Expense" | "Income" | "TransferIncome" | "TransferExpense"
export type GetAccount = { id: number; name: string; balance: number }
export type GetScheduledTransaction = { id: number; kind: ScheduledTransactionKinds; value: number; description: string | null; created_date: string; account_id: number | null; account_name: string | null; category_id: number | null; category_type: CategoryTypes | null; category_name: string | null; origin_account_id: number | null; origin_account_name: string | null; destination_account_id: number | null; destination_account_name: string | null; repeat: boolean; repeat_freq: RepeatFrequencies | null; repeat_interval: number | null; infinite_repeat: boolean | null; end_after_repeats: number | null; current_repeat_count: number | null; next_date: string | null }
export type InitialData = { accounts: GetAccount[]; categories: Category[]; scheduled_transactions: GetScheduledTransaction[] }
export type PatchTransaction = { value: number; description: string; date: string; account: number; category: number }
export type PatchTransfer = { origin_account: number; destination_account: number; value: number; description: string; date: string }
export type PostCategory = { categorytype: CategoryTypes; name: string }
export type PostScheduledTransaction = { kind: ScheduledTransactionKinds; value: number; description: string | null; created_date: string; account_id: number | null; category_id: number | null; origin_account_id: number | null; destination_account_id: number | null; repeat: boolean; repeat_freq: RepeatFrequencies | null; repeat_interval: number | null; infinite_repeat: boolean | null; end_after_repeats: number | null; current_repeat_count: number | null; next_date: string | null }
export type PostScheduledTransactionPay = { value: number; description: string; date: string; category_id: number | null; account_id: number | null; origin_account_id: number | null; destination_account_id: number | null }
export type PostTransaction = { value: number; description: string; date: string; category: number }
export type PostTransfer = { value: number; description: string; date: string }
export type RepeatFrequencies = "Days" | "Weeks" | "Months" | "Years"
export type ScheduledTransaction = { id: number; kind: ScheduledTransactionKinds; value: number; description: string | null; created_date: string; account_id: number | null; category_id: number | null; origin_account_id: number | null; destination_account_id: number | null; repeat: boolean; repeat_freq: RepeatFrequencies | null; repeat_interval: number | null; infinite_repeat: boolean | null; end_after_repeats: number | null; current_repeat_count: number | null; next_date: string | null }
export type ScheduledTransactionKinds = "Transaction" | "Transfer"
export type Transaction = { id: number; value: number; description: string; date: string; account: number; category: number }
export type TransactionTransferJoined = { id: number; value: number; description: string; date: string; category_id: number | null; category_type: CategoryTypes; category_name: string | null; account_id: number; account_name: string; from_account_id: number | null; from_account_name: string | null }
export type Transfer = { id: number; origin_account: number; destination_account: number; value: number; description: string; date: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
